import './globals.css';
import { Toaster } from 'sileo';

export const metadata = {
  title: 'Indicadores',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
	  <body className='bg-[#0f111a] font-sans'>
	  	{children}
    	<Toaster position='top-center' />	
      </body>
    </html>
  );
}
